# app/config/routing.yml
app.swagger_ui:
    path: /documentation
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /v1
