security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        app_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        oauth_token:                                   # Everyone can access the access token URL.
            pattern: ^/v1/token
            security: false
        api:
            pattern: ^/                                # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: false                           # Anonymous access is not allowed

    access_control:
        - { path: ^/v1, roles: IS_AUTHENTICATED_FULLY }
